# Data from beebeejump website
## Todos;
### Clean and visulaize
### Save the file
### Visulaize with power bi
### Make interactive dashboard

In [1]:
import opendatasets as od
import pandas as pd
import os
import plotly.express as px
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

%pip install opendatasets - -upgrade - -quiet
%pip install pandas - -quiet
%pip install scikit-learn
%pip install numpy - -upgrade - -quiet
%matplotlib inline

Note: you may need to restart the kernel to use updated packages.

Usage:
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] [-e] <vcs project url> ...
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] [-e] <local project path> ...
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] <archive url/path> ...

no such option: -u

Note: you may need to restart the kernel to use updated packages.

Usage:
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] [-e] <vcs project url> ...
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] [-e] <local project path> ...
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] <archive url/path> ...

no such option: -u

Requirement already satisfied: scikit-learn in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (1.2.0)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy>=1.17.3 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.9.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.2.0)

Usage:
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] [-e] <vcs project url> ...
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] [-e] <local project path> ...
  c:\Users\PC\AppData\Local\Programs\Python\Python310\python.exe -m pip install [options] <archive url/path> ...

no such option: -u

Note: you may need to restart the kernel to use updated packages.

# import libraries
import pandas as pd
import geopandas as gpd
import mapview as mv

# read data from csv file
df = pd.read_csv("../filename.csv", sep = ",", dtype=str)
# randomly sample few datapoints from this big dataset
d = df.sample(n=500, random_state=1)
# create a geopandas dataframe of latitude and longitude columns
latlong = gpd.GeoDataFrame(d, geometry=gpd.points_from_xy(d['Longitude'], d['Latitude']), crs='EPSG:4326')
# create an interactive map
mv.view(latlong)

In [2]:
df_mail = pd.read_excel("./beebeejump data4.xlsx")

In [3]:
df_mail.head()

,Email Address,First Name,Phone Number,CONFIRM_IP,LATITUDE,LONGITUDE,TIMEZONE,CC,REGION,Time,Date,Year-Quater,Year-month,Month,Year-seasons,Month-day,Hour
0,abiodunfolarin61@gmail.com,Abiodun,7033736307,197.210.77.106,11.29,7.75,Africa/Lagos,NG,KD,14:12:00,2023-05-07,Q2,2023-May,5,Rainy season,May-Sun,14
1,emmanueloladele5@gmail.com,Emmanuel Oladele,8060272941,102.89.23.229,6.49,3.41,Africa/Lagos,NG,LA,10:48:00,2023-05-07,Q2,2023-May,5,Rainy season,May-Sun,10
2,ezenwa101oxygen@gmail.com,Ezenwa,8020994158,197.210.70.91,8.97,7.57,Africa/Lagos,NG,FC,05:26:00,2023-05-07,Q2,2023-May,5,Rainy season,May-Sun,5
3,abdullahiumarjustice@gmail.com,Abdullahi Umar,7067411312,102.23.96.7,6.49,3.41,Africa/Lagos,NG,LA,18:12:00,2023-05-06,Q2,2023-May,5,Rainy season,May-Sat,18
4,extremerockintl@gmail.com,NSIKAK,8038951494,105.112.113.160,13.06,5.24,Africa/Lagos,NG,SO,19:08:00,2023-05-04,Q2,2023-May,5,Rainy season,May-Thu,19

In [4]:
df_mail.duplicated(subset=['Email Address']).sum()

0

In [9]:
df_mail

,Email Address,First Name,Phone Number,CONFIRM_IP,LATITUDE,LONGITUDE,TIMEZONE,CC,REGION,Time,Date,Year-Quater,Year-month,Month,Year-seasons,Month-day,Hour
0,abiodunfolarin61@gmail.com,Abiodun,7033736307,197.210.77.106,11.29,7.75,Africa/Lagos,NG,KD,14:12:00,2023-05-07,Q2,2023-May,5,Rainy season,May-Sun,14
1,emmanueloladele5@gmail.com,Emmanuel Oladele,8060272941,102.89.23.229,6.49,3.41,Africa/Lagos,NG,LA,10:48:00,2023-05-07,Q2,2023-May,5,Rainy season,May-Sun,10
2,ezenwa101oxygen@gmail.com,Ezenwa,8020994158,197.210.70.91,8.97,7.57,Africa/Lagos,NG,FC,05:26:00,2023-05-07,Q2,2023-May,5,Rainy season,May-Sun,5
3,abdullahiumarjustice@gmail.com,Abdullahi Umar,7067411312,102.23.96.7,6.49,3.41,Africa/Lagos,NG,LA,18:12:00,2023-05-06,Q2,2023-May,5,Rainy season,May-Sat,18
4,extremerockintl@gmail.com,NSIKAK,8038951494,105.112.113.160,13.06,5.24,Africa/Lagos,NG,SO,19:08:00,2023-05-04,Q2,2023-May,5,Rainy season,May-Thu,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2649,emekasampolo@gmail.com,NaN,NaN,192.3.45.50,NaN,NaN,NaN,NaN,NaN,16:08:00,2019-09-17,Q3,2019-Sep,9,Rainy season,Sep-Tue,16
2650,ajewoletimileyin67@gmail.Com,NaN,NaN,192.3.45.50,NaN,NaN,NaN,NaN,NaN,05:35:00,2019-09-17,Q3,2019-Sep,9,Rainy season,Sep-Tue,5
2651,obekpaemmanuel123@gmail.com,NaN,NaN,192.3.45.50,8.99,7.57,africa/lagos,ng,fc,17:48:00,2019-09-15,Q3,2019-Sep,9,Rainy season,Sep-Sun,17
2652,cuteib@gmail.com,NaN,NaN,192.3.45.50,NaN,NaN,NaN,NaN,NaN,07:29:00,2019-08-19,Q3,2019-Aug,8,Rainy season,Aug-Mon,7
2653,abdulgafarzainab@gmail.com,NaN,NaN,192.3.45.50,6.49,3.41,africa/lagos,ng,la,08:55:00,2019-05-28,Q2,2019-May,5,Rainy season,May-Tue,8

In [11]:
df_mail1 = df_mail.copy()

In [12]:
df_mail1.drop('CONFIRM_IP', inplace=True, axis=1)

In [13]:
df_mail1

,Email Address,First Name,Phone Number,LATITUDE,LONGITUDE,TIMEZONE,CC,REGION,Time,Date,Year-Quater,Year-month,Month,Year-seasons,Month-day,Hour
0,abiodunfolarin61@gmail.com,Abiodun,7033736307,11.29,7.75,Africa/Lagos,NG,KD,14:12:00,2023-05-07,Q2,2023-May,5,Rainy season,May-Sun,14
1,emmanueloladele5@gmail.com,Emmanuel Oladele,8060272941,6.49,3.41,Africa/Lagos,NG,LA,10:48:00,2023-05-07,Q2,2023-May,5,Rainy season,May-Sun,10
2,ezenwa101oxygen@gmail.com,Ezenwa,8020994158,8.97,7.57,Africa/Lagos,NG,FC,05:26:00,2023-05-07,Q2,2023-May,5,Rainy season,May-Sun,5
3,abdullahiumarjustice@gmail.com,Abdullahi Umar,7067411312,6.49,3.41,Africa/Lagos,NG,LA,18:12:00,2023-05-06,Q2,2023-May,5,Rainy season,May-Sat,18
4,extremerockintl@gmail.com,NSIKAK,8038951494,13.06,5.24,Africa/Lagos,NG,SO,19:08:00,2023-05-04,Q2,2023-May,5,Rainy season,May-Thu,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2649,emekasampolo@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16:08:00,2019-09-17,Q3,2019-Sep,9,Rainy season,Sep-Tue,16
2650,ajewoletimileyin67@gmail.Com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05:35:00,2019-09-17,Q3,2019-Sep,9,Rainy season,Sep-Tue,5
2651,obekpaemmanuel123@gmail.com,NaN,NaN,8.99,7.57,africa/lagos,ng,fc,17:48:00,2019-09-15,Q3,2019-Sep,9,Rainy season,Sep-Sun,17
2652,cuteib@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07:29:00,2019-08-19,Q3,2019-Aug,8,Rainy season,Aug-Mon,7
2653,abdulgafarzainab@gmail.com,NaN,NaN,6.49,3.41,africa/lagos,ng,la,08:55:00,2019-05-28,Q2,2019-May,5,Rainy season,May-Tue,8

In [14]:
df_mail1.to_csv('beebeejumpcleaned.csv', encoding='utf-8')